name: Gen androin sign

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test gen android sign

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: cd github-actions/gen-android-sign && npm i

      - name: Run tests
        run: cd github-actions/gen-android-sign && npm run test

      - uses: pCYSl5EDgo/cat@1.0.0
        name: Cat for GitHub Actions
        id: get_key
        with:
          path: github-actions/gen-android-sign/__tests__/test_key_b64.txt

      - uses: ./github-actions/gen-android-sign
        name: Generate sign file
        id: gen_key
        with:
          path: android/key.properties
          signingKeyBase64: ${{ steps.get_key.outputs.text }}
          alias: test_key
          keyStorePassword: android
          keyPassword: android

      - name: Verify
        run: |
          set -xe
          echo ${ANDROID_KEY_PROPERTIES}
          echo ${{ steps.gen_key.outputs.path }}
          cat android/key.properties

